### ISSUE TITLE
Question : Does this package identify Tenant DB via subdomain in request ?

### ISSUE THREAD

**Issue by z2z** [protosofia/ben10ant#3]
@ephiot 

Question : Does this package identify Tenant DB using subdomain in request ?

**Comment by ephiot** [comment]
Hi @z2z, thanks for your question!

You can implement a middleware that extract the subdomain and use it on the setTenantByKey method.

Would be something like this implementation https://github.com/protosofia/ben10ant/blob/master/src/Middlewares/CheckTenantByKey.php

Instead of a header you will get the subdomain.

You can use the Tenant::setTenantByKey('tenant key/subdomain/whatever') in any place on your code.
